#!/bin/bash
release="$(cat /etc/os-release | grep 'NAME="elementary OS"')"
if [ -n "$release" ]
then
    echo "You are using ElementaryOS. Updates will now install."
    cd /usr/share/themes/
    if [ -d macOS-Sierra/ ]
    then
        echo "Updating macOS-Sierra light GTK theme."
        cd macOS-Sierra/
        sudo git pull origin master
        cd ..
    else
        echo "Directory \"/usr/share/themes/macOS-Sierra/\" not found! Light GTK theme will not be updated."
    fi
    if [ -d macOS-Sierra-Dark/ ]
    then
        echo "Updating macOS-Sierra dark GTK theme."
        cd macOS-Sierra-Dark
        sudo git pull origin master
        cd ../
    else
        echo "Directory \"/usr/share/themes/macOS-Sierra-Dark/\" not found! Dark GTK theme will not be updated."
    fi
    cd /usr/share/icons/
    if [ -d la-capitaine-icon-theme/ ]
    then
        echo "Updating La Capitaine icon theme."
        cd la-capitaine-icon-theme
        sudo git pull origin master
    else
        echo "Directory \"/usr/share/icons/la-capitaine-icon-theme\" not found! Icon theme will not be updated."
    fi
    echo "Updates completed."
else
    echo "This script must be run on ElementaryOS! Download it at elementary.io"
fi
